<?php

$siteUrl = rtrim(env('SEO_SITE_URL', 'https://turancetechnologies.com'), '/');

return [
    'site_url' => $siteUrl,
    'site_name' => 'Turance Technologies',
    'tagline' => 'Excellence Delivered',
    'locale' => 'en_NG',
    'logo' => $siteUrl.'/assets/img/logo/logo.png',
    'favicon' => $siteUrl.'/assets/img/logo/favicon.png',
    'image' => $siteUrl.'/assets/img/service/service-inner-hero-thumb.jpg',
    'email' => 'support@turancetechnologies.com',
    'phone' => '+2349124948602',
    'address' => [
        'street' => 'No 3 Ademola Adetokunbo Crescent',
        'city' => 'Abuja',
        'region' => 'FCT',
        'country' => 'NG',
    ],
    'area_served' => ['Nigeria', 'United States', 'United Kingdom', 'United Arab Emirates', 'Worldwide'],
    'keywords' => [
        'website design company',
        'software development company',
        'mobile app development',
        'SaaS development agency',
        'branding agency',
        'web design Abuja',
        'Turance Technologies',
    ],
    'default' => [
        'title' => 'Web Design & Software Development Agency | Turance',
        'description' => 'Turance Technologies builds conversion-focused websites, mobile apps, SaaS platforms and brand systems for ambitious businesses in Nigeria and worldwide.',
        'route' => 'home',
        'priority' => '1.0',
        'changefreq' => 'weekly',
    ],
    'pages' => [
        'home' => [
            'title' => 'Web Design & Software Development Agency | Turance',
            'description' => 'Turn more visitors into customers with a fast, conversion-focused website, mobile app, SaaS platform or brand system built by Turance Technologies.',
            'route' => 'home',
            'priority' => '1.0',
            'changefreq' => 'weekly',
            'view' => 'index',
            'breadcrumb' => 'Home',
        ],
        'service.show' => [
            'title' => 'Web, App, SaaS & Branding Services | Turance',
            'description' => 'Compare clear starting prices and delivery options for conversion-focused websites, mobile apps, SaaS products, UX design and branding.',
            'route' => 'service.show',
            'priority' => '0.9',
            'changefreq' => 'weekly',
            'view' => 'services-overview',
            'breadcrumb' => 'Services',
        ],
        'services.web' => [
            'title' => 'Web Design Company in Abuja, Nigeria | Turance',
            'description' => 'Get a fast, SEO-ready website designed to build trust and generate qualified leads. Custom web design and development from Abuja for businesses worldwide.',
            'route' => 'services.web',
            'priority' => '0.9',
            'changefreq' => 'monthly',
            'service_type' => 'Website design and development',
            'view' => 'service-detail',
            'breadcrumb' => 'Web Design & Development',
            'parent_route' => 'service.show',
        ],
        'services.mobile' => [
            'title' => 'Mobile App Development Company | Turance',
            'description' => 'Launch a polished iOS and Android app with product strategy, UX, secure APIs, payments, analytics and app store support from one experienced team.',
            'route' => 'services.mobile',
            'priority' => '0.85',
            'changefreq' => 'monthly',
            'service_type' => 'Mobile app development',
            'view' => 'service-detail',
            'breadcrumb' => 'Mobile App Development',
            'parent_route' => 'service.show',
        ],
        'services.saas' => [
            'title' => 'SaaS Product Development Company | Turance',
            'description' => 'Build or improve a scalable SaaS product with clear onboarding, dashboards, subscriptions, permissions, analytics and integrations.',
            'route' => 'services.saas',
            'priority' => '0.85',
            'changefreq' => 'monthly',
            'service_type' => 'SaaS product design and development',
            'view' => 'service-detail',
            'breadcrumb' => 'SaaS Development',
            'parent_route' => 'service.show',
        ],
        'services.branding' => [
            'title' => 'Branding & Identity Design Agency | Turance',
            'description' => 'Build a distinctive brand with positioning, messaging, logo design, typography, colour systems, guidelines and rollout-ready assets.',
            'route' => 'services.branding',
            'priority' => '0.8',
            'changefreq' => 'monthly',
            'service_type' => 'Branding and identity design',
            'view' => 'service-detail',
            'breadcrumb' => 'Branding & Identity',
            'parent_route' => 'service.show',
        ],
        'contact.show' => [
            'title' => 'Request a Website or App Quote | Turance',
            'description' => 'Tell Turance Technologies about your website, app, SaaS or branding project. Get a practical next step, estimated scope and clear delivery path.',
            'route' => 'contact.show',
            'priority' => '0.85',
            'changefreq' => 'monthly',
            'view' => 'contact',
            'breadcrumb' => 'Request a Quote',
        ],
        'privacy.show' => [
            'title' => 'Privacy Policy | Turance Technologies',
            'description' => 'Learn how Turance Technologies collects, uses and protects information submitted through this website.',
            'route' => 'privacy.show',
            'priority' => '0.4',
            'changefreq' => 'yearly',
            'view' => 'legal-page',
            'breadcrumb' => 'Privacy Policy',
        ],
        'terms.show' => [
            'title' => 'Terms of Use | Turance Technologies',
            'description' => 'Read the terms that apply to using the Turance Technologies website and submitting project enquiries.',
            'route' => 'terms.show',
            'priority' => '0.4',
            'changefreq' => 'yearly',
            'view' => 'legal-page',
            'breadcrumb' => 'Terms of Use',
        ],
    ],
    'service_items' => [
        [
            'name' => 'Website design and development',
            'route' => 'services.web',
            'description' => 'Premium websites that build trust, generate qualified enquiries, and support long-term search visibility.',
        ],
        [
            'name' => 'Mobile app development',
            'route' => 'services.mobile',
            'description' => 'User-friendly mobile apps with strategy, UX, secure backends, payments, notifications, and launch support.',
        ],
        [
            'name' => 'SaaS product design and development',
            'route' => 'services.saas',
            'description' => 'Scalable SaaS platforms with onboarding, dashboards, subscriptions, analytics, and integrations.',
        ],
        [
            'name' => 'Branding and identity design',
            'route' => 'services.branding',
            'description' => 'Premium brand systems with positioning, messaging, visual identity, and rollout-ready assets.',
        ],
    ],
    'home_faqs' => [
        ['question' => 'What types of businesses do you work with?', 'answer' => 'We work with ambitious organisations at different stages, from growing businesses to established teams modernising critical digital products.'],
        ['question' => 'Can Turance Technologies improve an existing product?', 'answer' => 'Yes. We can assess an existing website, application or workflow, identify the most valuable improvements and deliver them in focused phases.'],
        ['question' => 'Do you provide both design and development?', 'answer' => 'Yes. Strategy, product design and engineering can be delivered as one engagement or shaped around the capability you already have.'],
        ['question' => 'How long does a typical project take?', 'answer' => 'Timing depends on scope, complexity and review cycles. We establish a realistic delivery plan after discovery and keep milestones visible throughout.'],
        ['question' => 'Do you provide maintenance after launch?', 'answer' => 'Yes. Ongoing maintenance, monitoring, optimisation and technical support can be included around the needs of the product.'],
        ['question' => 'Can you work with an existing internal team?', 'answer' => 'Absolutely. We can extend an internal product or engineering team, own a defined workstream or provide specialist guidance.'],
        ['question' => 'How do you determine project pricing?', 'answer' => 'Pricing is based on the agreed scope, technical complexity, delivery model and timeline. Discovery gives us the detail needed to quote clearly.'],
        ['question' => 'How do we start a project?', 'answer' => 'Share what you are building, improving or trying to solve. We will review the context and arrange a focused first conversation.'],
    ],
    'services_faqs' => [
        ['question' => 'How do we choose the right engagement?', 'answer' => 'We use your goals, timeline, current assets and technical needs to shape the right level of work. The first conversation is about clarity, not forcing a package.'],
        ['question' => 'Can you improve an existing brand or product?', 'answer' => 'Yes. We identify what already works, preserve the strongest foundations and focus investment on the areas limiting clarity, adoption or growth.'],
        ['question' => 'Do you handle both design and development?', 'answer' => 'Yes. Strategy, product design, engineering, testing and launch can stay aligned under one delivery team instead of being divided across several vendors.'],
        ['question' => 'What happens after launch?', 'answer' => 'We can support optimisation, analytics review, maintenance and new feature delivery. Launch is the beginning of real-world learning, not the end of the relationship.'],
    ],
];
