<?php

return [
    'web' => [
        'name' => 'Web Development',
        'eyebrow' => 'Web experiences',
        'title' => 'Websites engineered to earn attention and turn it into action.',
        'lead' => 'We design and build distinctive, fast and conversion-focused websites for organisations that need their digital presence to carry real commercial weight.',
        'image' => 'assets/img/service/service-inner-hero-thumb.jpg',
        'image_alt' => 'Premium website design interface',
        'engagement' => '8–16 weeks',
        'fit' => 'Growth-minded teams',
        'hero_word' => 'Digital',
        'visual_code' => 'WEB / 01',
        'visual_details' => ['Structure', 'Performance', 'Conversion'],
        'overview_title' => 'A website should do more than confirm that your business exists.',
        'overview' => [
            'It should make your value immediately clear, establish confidence and guide the right people towards a meaningful next step.',
            'We bring strategy, interface design, content structure and engineering into one considered process—creating a site that feels refined while remaining practical to manage and ready to grow.',
        ],
        'highlights' => [
            'Positioning and conversion architecture',
            'Responsive UI/UX design systems',
            'Accessible, SEO-ready development',
            'Analytics, integrations and launch support',
        ],
        'process' => [
            ['name' => 'Discover', 'copy' => 'Clarify the audience, commercial goal, current gaps and the decisions the website must support.'],
            ['name' => 'Structure', 'copy' => 'Shape the sitemap, content hierarchy and conversion paths before visual design begins.'],
            ['name' => 'Design & build', 'copy' => 'Create the interface system and develop a fast, responsive experience across devices.'],
            ['name' => 'Launch & improve', 'copy' => 'Test, deploy, measure and refine the experience using real performance signals.'],
        ],
        'deliverables' => [
            'Digital strategy and page architecture',
            'Custom responsive interface design',
            'Content and conversion guidance',
            'CMS or application development',
            'Technical SEO and performance setup',
            'Quality assurance and launch support',
        ],
        'faqs' => [
            ['question' => 'How long does a professional website take?', 'answer' => 'Most focused website engagements take eight to sixteen weeks. Scope, content readiness, integrations and review cycles determine the final schedule.'],
            ['question' => 'Can you redesign an existing website?', 'answer' => 'Yes. We assess what is worth retaining, what is holding the experience back and how to migrate content or functionality without unnecessary disruption.'],
            ['question' => 'Will our team be able to manage it?', 'answer' => 'Yes. We choose a content workflow that suits your team and provide a clear handover so routine updates do not depend on a developer.'],
        ],
    ],
    'mobile' => [
        'name' => 'Mobile Development',
        'eyebrow' => 'Mobile products',
        'title' => 'Mobile experiences people understand from the first tap.',
        'lead' => 'We turn product ideas and operational needs into focused mobile applications with thoughtful journeys, dependable engineering and room to evolve.',
        'image' => 'assets/img/service/mobile-development-hero-v2.webp',
        'image_alt' => 'Mobile banking application displayed across two smartphones',
        'engagement' => '10–24 weeks',
        'fit' => 'Products built to scale',
        'hero_word' => 'Mobile',
        'visual_code' => 'APP / 02',
        'visual_details' => ['Journeys', 'Interface', 'Systems'],
        'overview_title' => 'The best mobile products make complexity feel almost invisible.',
        'overview' => [
            'A successful app needs more than a collection of screens. It needs a clear reason to exist, a focused first release and an experience that respects the way people actually behave on mobile.',
            'We help shape the product, prototype important journeys and build the application, APIs and operational tools needed to support it after launch.',
        ],
        'highlights' => [
            'Product definition and MVP planning',
            'Native-feeling cross-platform experiences',
            'Secure APIs, payments and notifications',
            'Store preparation and post-launch support',
        ],
        'process' => [
            ['name' => 'Define', 'copy' => 'Prioritise the user problem, core journeys and the smallest release capable of proving value.'],
            ['name' => 'Prototype', 'copy' => 'Make the critical interactions tangible early and test assumptions before full development.'],
            ['name' => 'Engineer', 'copy' => 'Build the mobile application, backend services and integrations as one dependable system.'],
            ['name' => 'Release', 'copy' => 'Complete quality checks, store preparation, analytics and a measured rollout plan.'],
        ],
        'deliverables' => [
            'Product scope and feature roadmap',
            'User flows and interactive prototypes',
            'iOS and Android application',
            'Backend APIs and admin tooling',
            'Payments, notifications and analytics',
            'Store submission and launch support',
        ],
        'faqs' => [
            ['question' => 'Should we begin with an MVP?', 'answer' => 'Usually. A focused first release reduces risk and gives the team real evidence before committing to less certain features.'],
            ['question' => 'Can you build the backend and admin dashboard too?', 'answer' => 'Yes. We can deliver the mobile experience, APIs, data model, integrations and the internal tools needed to operate it.'],
            ['question' => 'How long does it take to launch?', 'answer' => 'A focused mobile MVP commonly takes ten to twenty-four weeks, depending on product complexity, integrations and release requirements.'],
        ],
    ],
    'saas' => [
        'name' => 'SaaS Development',
        'eyebrow' => 'Scalable platforms',
        'title' => 'SaaS products that make complicated work feel controlled.',
        'lead' => 'We shape and build digital platforms around real workflows—bringing product strategy, interface clarity and scalable engineering into one coherent system.',
        'image' => 'assets/img/service/service-single4.jpg',
        'image_alt' => 'SaaS platform dashboard experience',
        'engagement' => '12–28 weeks',
        'fit' => 'Founders and operators',
        'hero_word' => 'Systems',
        'visual_code' => 'SAAS / 03',
        'visual_details' => ['Product', 'Workflow', 'Scale'],
        'overview_title' => 'A strong SaaS product creates clarity for users and leverage for the business.',
        'overview' => [
            'The challenge is rarely building more features. It is deciding which workflows matter, how roles and data should connect and what makes the product valuable enough to become part of someone’s routine.',
            'We translate that complexity into a focused product architecture, a calm interface and a technical foundation that can support new customers, integrations and operating demands.',
        ],
        'highlights' => [
            'MVP strategy and product architecture',
            'Roles, workflows and dashboard design',
            'Subscriptions, integrations and automation',
            'Scalable backend and interface systems',
        ],
        'process' => [
            ['name' => 'Model the product', 'copy' => 'Define users, roles, core workflows, business rules and the value the first release must prove.'],
            ['name' => 'Design the system', 'copy' => 'Turn complex tasks into clear journeys, reusable patterns and an understandable product structure.'],
            ['name' => 'Build in phases', 'copy' => 'Engineer the platform around stable foundations and review working increments throughout delivery.'],
            ['name' => 'Learn and scale', 'copy' => 'Instrument the product, observe adoption and prioritise improvements using evidence.'],
        ],
        'deliverables' => [
            'Product requirements and release plan',
            'Information architecture and UX design',
            'Responsive SaaS application',
            'Permissions and account management',
            'Billing, analytics and integrations',
            'Deployment and growth roadmap',
        ],
        'faqs' => [
            ['question' => 'Can you build an MVP first and scale it later?', 'answer' => 'Yes. We define an MVP that proves the central value while establishing sound architecture for the capabilities that are likely to follow.'],
            ['question' => 'Can you improve an existing SaaS platform?', 'answer' => 'Yes. We can audit product experience and architecture, then modernise focused areas without forcing an unnecessary full rebuild.'],
            ['question' => 'Do you support the product after launch?', 'answer' => 'Yes. Ongoing product development, monitoring, optimisation and technical support can be shaped around your operating model.'],
        ],
    ],
    'branding' => [
        'name' => 'Branding & Identity',
        'eyebrow' => 'Brand systems',
        'title' => 'Make your brand unmistakable.',
        'lead' => 'We create strategic identities that help ambitious businesses earn recognition, communicate with clarity and show up with confidence.',
        'hero_disciplines' => ['Positioning', 'Verbal identity', 'Visual system', 'Brand rollout'],
        'image' => 'assets/img/service/branding-identity-hero-v2.webp',
        'image_alt' => 'Brand identity design system presentation',
        'engagement' => '4–10 weeks',
        'fit' => 'New and evolving brands',
        'hero_word' => 'Identity',
        'visual_code' => 'BRAND / 04',
        'visual_details' => ['Position', 'Voice', 'Visual'],
        'overview_title' => 'Before a client studies your offer, they form an impression of your brand.',
        'overview' => [
            'A strong identity makes that impression intentional. It creates recognition, gives your message a consistent voice and helps every touchpoint feel like part of the same business.',
            'We begin with positioning and audience insight, then translate that thinking into a flexible visual system your team can apply confidently across digital and physical channels.',
        ],
        'highlights' => [
            'Positioning and audience direction',
            'Identity, typography and colour systems',
            'Messaging and tone of voice',
            'Guidelines and rollout-ready assets',
        ],
        'process' => [
            ['name' => 'Discover', 'copy' => 'Understand the business, audience, market context and the perceptions the brand needs to change or strengthen.'],
            ['name' => 'Position', 'copy' => 'Clarify the distinctive idea, personality, message and creative territory the identity should own.'],
            ['name' => 'Create', 'copy' => 'Design the identity system and test how it behaves across the touchpoints that matter.'],
            ['name' => 'Activate', 'copy' => 'Prepare practical guidelines, templates and assets so the brand launches with consistency.'],
        ],
        'deliverables' => [
            'Brand discovery and positioning',
            'Messaging and tone direction',
            'Logo and identity system',
            'Typography and colour specifications',
            'Digital and presentation applications',
            'Brand guidelines and source assets',
        ],
        'faqs' => [
            ['question' => 'What is included in a branding project?', 'answer' => 'The scope can include positioning, messaging, identity design, typography, colour, templates, rollout assets and practical brand guidelines.'],
            ['question' => 'Can you refresh an existing brand?', 'answer' => 'Yes. We assess what carries useful recognition and what needs to change, then shape an evolution that feels deliberate rather than disconnected.'],
            ['question' => 'Will we receive editable assets and guidelines?', 'answer' => 'Yes. Your handover includes the agreed source files, export formats and clear guidance for applying the identity consistently.'],
        ],
    ],
];
