@extends('admin.project-management.layout', ['title' => 'Board'])

@section('project-content')
    <section class="panel pm-hero"><div><span class="eyebrow">{{ $project->project_number }} · Kanban</span><h2>Move work forward with a board the team can trust.</h2><p>Drag a card between columns or use its keyboard controls. Positions and status are saved transactionally, so a refresh keeps the same order.</p></div><div class="pm-actions"><a class="ghost-button" href="{{ route('admin.project-management.projects.show', $project) }}">Project summary</a><a class="button" href="#new-task">New task</a></div></section>

    <section class="panel pm-panel"><div class="pm-inline-form"><div class="field"><label for="board-assignee">Assignee</label><select id="board-assignee" data-board-filter="assignee"><option value="">Everyone</option>@foreach ($members as $member)<option value="{{ $member->id }}">{{ $member->name }}</option>@endforeach</select></div><div class="field"><label for="board-priority">Priority</label><select id="board-priority" data-board-filter="priority"><option value="">Every priority</option>@foreach ($priorities as $priority)<option value="{{ $priority }}">{{ Str::headline($priority) }}</option>@endforeach</select></div><label class="pm-chip" style="gap:7px; margin-bottom:1px"><input type="checkbox" data-board-filter="mine" value="{{ \App\Support\ProjectManagementAccess::user()?->id }}"> My tasks</label><label class="pm-chip" style="gap:7px; margin-bottom:1px"><input type="checkbox" data-board-filter="overdue"> Overdue</label><button class="ghost-button" type="button" data-reset-board-filters>Reset filters</button></div></section>

    <section class="pm-board" data-project-board data-project-id="{{ $project->id }}">
        @foreach ($columns as $column)
            <article class="pm-column" data-column-id="{{ $column->id }}" data-column-name="{{ $column->name }}"><div class="pm-column-head"><div><strong>{{ $column->name }}</strong><span> · <span data-column-count>{{ $tasksByColumn->get($column->id, collect())->count() }}</span></span></div><span style="width:9px;height:9px;border-radius:50%;background:{{ $column->color }}"></span></div><div class="pm-column-list" data-column-list tabindex="0" aria-label="{{ $column->name }} tasks">@foreach ($tasksByColumn->get($column->id, collect()) as $task)<article class="pm-task-card" draggable="true" data-task-card data-task-id="{{ $task->id }}" data-assignee="{{ $task->assignee_id ?: '' }}" data-priority="{{ $task->priority }}" data-overdue="{{ $task->is_overdue ? '1' : '0' }}"><div class="pm-task-top"><span class="pm-task-key">{{ $task->task_key }}</span><span class="pm-chip {{ $task->priority === 'urgent' ? 'pm-chip--danger' : '' }}">{{ Str::headline($task->priority) }}</span></div><h4><a href="{{ route('admin.project-management.tasks.show', $task) }}">{{ $task->title }}</a></h4>@if ($task->labels->isNotEmpty())<div class="pm-card-labels">@foreach ($task->labels as $label)<span style="background:{{ $label->color }}22;color:{{ $label->color }}">{{ $label->name }}</span>@endforeach</div>@endif<div class="pm-task-bottom"><span class="{{ $task->is_overdue ? 'is-overdue' : '' }}">{{ $task->is_overdue ? 'Overdue' : (optional($task->due_on)->format('M d') ?: 'No due date') }}</span><span>{{ $task->assignee ? Str::upper(Str::substr($task->assignee->name, 0, 1)) : '—' }} · {{ $task->comments_count }} comments</span></div><div class="pm-task-bottom"><span>{{ $task->subtasks_count ? $task->completed_subtasks_count.'/'.$task->subtasks_count.' subtasks' : 'No subtasks' }}</span><span class="pm-actions"><button type="button" class="ghost-button" style="padding:4px 7px;font-size:10px" data-keyboard-move="previous" aria-label="Move {{ $task->task_key }} to previous column">←</button><button type="button" class="ghost-button" style="padding:4px 7px;font-size:10px" data-keyboard-move="next" aria-label="Move {{ $task->task_key }} to next column">→</button></span></div></article>@endforeach</div></article>
        @endforeach
    </section>

    <div class="pm-grid-wide" id="new-task">
        <section class="panel pm-panel"><div class="pm-panel-head"><div><h3>Create task</h3><p>Task keys are generated from the project key and a locked sequence.</p></div></div><form method="POST" action="{{ route('admin.project-management.tasks.store', $project) }}">@csrf<div class="pm-form-grid"><div class="field-full"><label for="task-title">Title</label><input id="task-title" name="title" required placeholder="Prepare client review notes"></div><div class="field"><label for="task-type">Type</label><select id="task-type" name="type">@foreach ($taskTypes as $type)<option value="{{ $type }}">{{ Str::headline($type) }}</option>@endforeach</select></div><div class="field"><label for="task-priority">Priority</label><select id="task-priority" name="priority">@foreach ($priorities as $priority)<option value="{{ $priority }}" @selected($priority === 'medium')>{{ Str::headline($priority) }}</option>@endforeach</select></div><div class="field"><label for="task-column">Column</label><select id="task-column" name="board_column_id">@foreach ($columns as $column)<option value="{{ $column->id }}">{{ $column->name }}</option>@endforeach</select></div><div class="field"><label for="task-assignee">Assignee</label><select id="task-assignee" name="assignee_id"><option value="">Unassigned</option>@foreach ($members as $member)<option value="{{ $member->id }}">{{ $member->name }}</option>@endforeach</select></div><div class="field"><label for="task-due">Due date</label><input id="task-due" type="date" name="due_on"></div><div class="field"><label for="task-hours">Estimated hours</label><input id="task-hours" type="number" min="0" step="0.25" name="estimated_hours"></div><div class="field"><label for="task-points">Story points</label><input id="task-points" type="number" min="0" step="0.5" name="story_points"></div><div class="field-full"><label for="task-description">Description</label><textarea id="task-description" name="description" rows="4" placeholder="Keep the acceptance context clear."></textarea></div>@if ($labels->isNotEmpty())<div class="field-full"><label>Labels</label><div class="pm-actions" style="margin-top:8px">@foreach ($labels as $label)<label class="pm-chip" style="gap:6px"><input type="checkbox" name="label_ids[]" value="{{ $label->id }}">{{ $label->name }}</label>@endforeach</div></div>@endif</div><div class="pm-form-actions"><button class="button" type="submit">Create task</button></div></form></section>
        <div class="pm-stack"><section class="panel pm-panel"><div class="pm-panel-head"><div><h3>Board columns</h3><p>Remove only empty columns.</p></div></div><div class="pm-list">@foreach ($columns as $column)<div class="pm-list-item"><div><strong>{{ $column->name }}</strong><span>{{ $column->is_done ? 'Completion column' : 'Open work' }}</span></div><form method="POST" action="{{ route('admin.project-management.columns.destroy', $column) }}">@csrf @method('DELETE')<button class="pm-icon-link" type="submit">Remove</button></form></div>@endforeach</div><form method="POST" action="{{ route('admin.project-management.columns.store', $project) }}" style="margin-top:14px">@csrf<div class="pm-inline-form"><div class="field"><label for="column-name">New column</label><input id="column-name" name="name" required placeholder="QA ready"></div><div class="field"><label for="column-color">Colour</label><input id="column-color" type="text" name="color" value="#b8860b"></div><button class="ghost-button" type="submit">Add</button></div></form></section><section class="panel pm-panel"><div class="pm-panel-head"><div><h3>Labels</h3><p>Keep board filters meaningful.</p></div></div><div class="pm-actions">@forelse ($labels as $label)<span class="pm-chip" style="border-color:{{ $label->color }}66">{{ $label->name }}</span>@empty<span class="pm-muted">No labels yet.</span>@endforelse</div><form method="POST" action="{{ route('admin.project-management.labels.store', $project) }}" style="margin-top:14px">@csrf<div class="pm-inline-form"><div class="field"><label for="label-name">New label</label><input id="label-name" name="name" required placeholder="Client review"></div><div class="field"><label for="label-color">Colour</label><input id="label-color" type="text" name="color" value="#b8860b"></div><button class="ghost-button" type="submit">Add</button></div></form></section></div>
    </div>
@endsection

@push('scripts')
    <script>
        (() => {
            const board = document.querySelector('[data-project-board]');
            if (!board) return;
            const csrf = document.querySelector('input[name="_token"]')?.value;
            const columns = [...board.querySelectorAll('[data-column-id]')];
            let dragged = null;
            const save = async (card, column, position) => {
                const response = await fetch('{{ url('/admin/project-management/tasks') }}/' + card.dataset.taskId + '/move', { method: 'PATCH', headers: {'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':csrf}, body: JSON.stringify({board_column_id: column.dataset.columnId, position}) });
                if (!response.ok) throw new Error('Task position could not be saved.');
            };
            const refreshCounts = () => columns.forEach(column => column.querySelector('[data-column-count]').textContent = column.querySelectorAll('[data-task-card]:not([hidden])').length);
            board.querySelectorAll('[data-task-card]').forEach(card => {
                card.addEventListener('dragstart', () => { dragged = card; card.classList.add('is-dragging'); });
                card.addEventListener('dragend', () => { dragged = null; card.classList.remove('is-dragging'); });
                card.querySelector('[data-keyboard-move="previous"]')?.addEventListener('click', () => moveByKeyboard(card, -1));
                card.querySelector('[data-keyboard-move="next"]')?.addEventListener('click', () => moveByKeyboard(card, 1));
            });
            const moveByKeyboard = async (card, delta) => {
                const current = columns.findIndex(column => column.contains(card));
                const target = columns[current + delta];
                if (!target) return;
                target.querySelector('[data-column-list]').append(card);
                try { await save(card, target, target.querySelectorAll('[data-task-card]').length - 1); refreshCounts(); } catch (error) { window.location.reload(); }
            };
            columns.forEach(column => {
                const list = column.querySelector('[data-column-list]');
                list.addEventListener('dragover', event => { event.preventDefault(); if (dragged) list.append(dragged); });
                list.addEventListener('drop', async event => { event.preventDefault(); if (!dragged) return; try { await save(dragged, column, [...list.querySelectorAll('[data-task-card]')].indexOf(dragged)); refreshCounts(); } catch (error) { window.location.reload(); } });
            });
            const applyFilters = () => { const assignee = document.querySelector('[data-board-filter="assignee"]').value; const priority = document.querySelector('[data-board-filter="priority"]').value; const mine = document.querySelector('[data-board-filter="mine"]').checked; const overdue = document.querySelector('[data-board-filter="overdue"]').checked; board.querySelectorAll('[data-task-card]').forEach(card => { card.hidden = (assignee && card.dataset.assignee !== assignee) || (priority && card.dataset.priority !== priority) || (mine && card.dataset.assignee !== document.querySelector('[data-board-filter="mine"]').value) || (overdue && card.dataset.overdue !== '1'); }); refreshCounts(); };
            document.querySelectorAll('[data-board-filter]').forEach(input => input.addEventListener('change', applyFilters));
            document.querySelector('[data-reset-board-filters]')?.addEventListener('click', () => { document.querySelectorAll('[data-board-filter]').forEach(input => { if (input.type === 'checkbox') input.checked = false; else input.value = ''; }); applyFilters(); });
        })();
    </script>
@endpush
