@extends('admin.project-management.layout', ['title' => $project->name])

@section('project-content')
    <div class="pm-project-view" data-read-only="{{ $canManageWorkspace ? '0' : '1' }}">
    <section class="panel pm-hero"><div><span class="eyebrow">{{ $project->project_number }} · {{ Str::headline($project->status) }}</span><h2>{{ $project->name }}</h2><p>{{ $project->description ?: 'A shared delivery workspace for the project team.' }}</p><div class="pm-project-meta" style="margin-top:14px"><span>{{ $project->client_company ?: $project->client_name ?: 'Internal project' }}</span><span>·</span><span>Manager: {{ $project->projectManager?->name ?: 'Unassigned' }}</span><span>·</span><span>Due {{ optional($project->ends_on)->format('M d, Y') ?: 'not set' }}</span></div></div><div class="pm-actions"><a class="button" href="{{ route('admin.project-management.board', $project) }}">Open board</a><a class="ghost-button" href="{{ route('admin.project-management.projects') }}">All projects</a></div></section>

    <div class="pm-stat-row"><div class="panel pm-stat"><strong>{{ $project->progress_percentage }}%</strong><span>Project progress</span></div><div class="panel pm-stat"><strong>{{ $project->tasks_count }}</strong><span>Total tasks</span></div><div class="panel pm-stat"><strong>{{ $project->completed_tasks_count }}</strong><span>Completed tasks</span></div></div>

    <nav class="pm-tabs"><a class="active" href="{{ route('admin.project-management.projects.show', $project) }}">Summary</a><a href="{{ route('admin.project-management.board', $project) }}">Board</a><a href="{{ route('admin.project-management.backlog', $project) }}">Backlog</a><a href="{{ route('admin.project-management.sprints', $project) }}">Sprints</a><a href="{{ route('admin.project-management.settings', $project) }}">Settings</a></nav>

    <div class="pm-detail-grid">
        <div class="pm-stack">
            <section class="panel pm-panel"><div class="pm-panel-head"><div><h3>Work in this project</h3><p>Open task details for inline updates, comments, time, and files.</p></div><a class="pm-icon-link" href="{{ route('admin.project-management.board', $project) }}">Move work →</a></div><div class="pm-table-wrap"><table class="pm-table"><thead><tr><th>Task</th><th>Status</th><th>Assignee</th><th>Priority</th><th>Due</th></tr></thead><tbody>@forelse ($tasks as $task)<tr><td><a class="pm-icon-link" href="{{ route('admin.project-management.tasks.show', $task) }}">{{ $task->task_key }}</a><strong><a href="{{ route('admin.project-management.tasks.show', $task) }}">{{ $task->title }}</a></strong><span class="pm-muted">{{ $task->subtasks_count ? $task->completed_subtasks_count.'/'.$task->subtasks_count.' subtasks · ' : '' }}{{ $task->comments_count }} comments</span></td><td><span class="pm-chip">{{ Str::headline($task->status) }}</span></td><td>{{ $task->assignee?->name ?: 'Unassigned' }}</td><td><span class="pm-chip {{ $task->priority === 'urgent' ? 'pm-chip--danger' : '' }}">{{ Str::headline($task->priority) }}</span></td><td class="{{ $task->is_overdue ? 'pm-chip--danger' : '' }}">{{ optional($task->due_on)->format('M d, Y') ?: '—' }}</td></tr>@empty<tr><td colspan="5"><div class="pm-empty">No tasks yet. <a class="pm-icon-link" href="{{ route('admin.project-management.board', $project) }}">Create one on the board →</a></div></td></tr>@endforelse</tbody></table></div></section>
            <section class="panel pm-panel"><div class="pm-panel-head"><div><h3>Project discussion</h3><p>Keep context close to the delivery record. Mentions notify project members.</p></div></div><div class="pm-list">@forelse ($comments as $comment)<div class="pm-list-item"><div><strong>{{ $comment->user?->name ?: 'Team member' }}</strong><span>{{ $comment->created_at->diffForHumans() }}</span><p style="margin:7px 0 0; white-space:pre-wrap; line-height:1.5">{{ $comment->body }}</p></div></div>@empty<div class="pm-empty">No project comments yet.</div>@endforelse</div><form method="POST" action="{{ route('admin.project-management.comments.store', $project) }}" style="margin-top:15px">@csrf<div class="field"><label for="project-comment">Add a comment</label><textarea id="project-comment" name="body" rows="3" maxlength="10000" required placeholder="Share a decision, risk, or handoff note. Use @name to mention a teammate."></textarea></div><div class="pm-form-actions"><button class="button" type="submit">Post comment</button></div></form></section>
        </div>
        <aside class="pm-stack">
            <section class="panel pm-panel"><div class="pm-panel-head"><div><h3>Team</h3><p>{{ $project->members->count() }} people connected.</p></div></div><div class="pm-list">@forelse ($project->members as $member)<div class="pm-list-item"><div><strong>{{ $member->name }}</strong><span>{{ Str::headline($member->pivot->role ?? 'member') }}{{ $member->job_title ? ' · '.$member->job_title : '' }}</span></div><span class="pm-avatar">{{ Str::upper(Str::substr($member->name, 0, 1)) }}</span></div>@empty<div class="pm-empty">No members yet.</div>@endforelse</div><form class="pm-inline-form" method="POST" action="{{ route('admin.project-management.members.store', $project) }}" style="margin-top:14px">@csrf<div class="field"><label for="member-id">Add member</label><select id="member-id" name="user_id"><option value="">Choose a person</option>@foreach ($members as $member)<option value="{{ $member->id }}">{{ $member->name }}</option>@endforeach</select></div><div class="field"><label for="member-role">Role</label><select id="member-role" name="role"><option value="member">Member</option><option value="viewer">Viewer</option><option value="manager">Manager</option></select></div><button class="button" type="submit">Add</button></form></section>
            <section class="panel pm-panel"><div class="pm-panel-head"><div><h3>Milestones</h3><p>Progress is derived from related tasks.</p></div></div><div class="pm-list">@forelse ($project->milestones as $milestone)<div class="pm-list-item"><div><strong>{{ $milestone->title }}</strong><span>{{ optional($milestone->due_on)->format('M d, Y') ?: 'No date' }} · {{ $milestone->progress_percentage }}%</span></div><span class="pm-chip">{{ Str::headline($milestone->status) }}</span></div>@empty<div class="pm-empty">No milestones yet.</div>@endforelse</div><form method="POST" action="{{ route('admin.project-management.milestones.store', $project) }}" style="margin-top:14px">@csrf<div class="field"><label for="milestone-title">New milestone</label><input id="milestone-title" name="title" required placeholder="Release candidate"></div><div class="field" style="margin-top:9px"><label for="milestone-due">Due date</label><input id="milestone-due" type="date" name="due_on"></div><div class="pm-form-actions"><button class="ghost-button" type="submit">Add milestone</button></div></form></section>
            <section class="panel pm-panel"><div class="pm-panel-head"><div><h3>Recent activity</h3><p>Immutable delivery history.</p></div></div><div class="pm-list">@forelse ($recentActivity as $activity)<div class="pm-list-item"><div><strong>{{ Str::headline(str_replace('.', ' ', $activity->action)) }}</strong><span>{{ $activity->actor?->name ?: 'System' }} · {{ $activity->created_at->diffForHumans() }}</span></div></div>@empty<div class="pm-empty">No activity yet.</div>@endforelse</div></section>
        </aside>
    </div>

    <section class="panel pm-panel"><div class="pm-panel-head"><div><h3>Project settings</h3><p>Authorized managers can adjust delivery metadata and the progress calculation.</p></div><a class="button" href="{{ route('admin.project-management.settings', $project) }}">Edit settings</a></div><div class="pm-callout">{{ $project->project_brief ?: 'Add a project brief in Settings so the team has a durable source of truth for scope and delivery constraints.' }}</div></section>
    </div>
@endsection
