@extends('admin.project-management.layout', ['title' => $includeArchived ? 'Archived Projects' : 'Projects'])

@section('project-content')
    <div class="pm-project-list" data-read-only="{{ $canManageWorkspace ? '0' : '1' }}">
    <section class="panel pm-hero"><div><span class="eyebrow">{{ $includeArchived ? 'History' : 'Portfolio' }}</span><h2>{{ $includeArchived ? 'Archived projects stay searchable.' : 'Projects with a clear next move.' }}</h2><p>{{ $includeArchived ? 'Restore a project when delivery resumes, or keep the record for reference.' : ($canCreateProject ? 'Create an internal or client project, assign a manager, and bring the team into the same delivery rhythm.' : ($canManageWorkspace ? 'Coordinate delivery across the existing project portfolio.' : 'Review the projects and delivery records available to your account.')) }}</p></div><div class="pm-actions">@if ($canCreateProject)<a class="button" href="{{ route('admin.project-management.projects.create') }}">New project</a>@endif<a class="ghost-button" href="{{ route('admin.projects.index') }}">Project files</a></div></section>
    <form class="panel pm-panel" method="GET" action="{{ route('admin.project-management.projects') }}"><div class="pm-inline-form"><div class="field"><label for="project-search">Search</label><input id="project-search" name="q" value="{{ request('q') }}" placeholder="Project key, name, or client"></div><div class="field"><label for="project-status">Status</label><select id="project-status" name="status"><option value="">All statuses</option>@foreach ($statuses as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ Str::headline($status) }}</option>@endforeach</select></div><button class="button" type="submit">Search</button><a class="ghost-button" href="{{ $includeArchived ? route('admin.project-management.archived') : route('admin.project-management.projects') }}">Reset</a></div></form>
    <section class="pm-grid-wide">
        @forelse ($projects as $project)
            <article class="panel pm-panel pm-project-card"><div class="pm-project-card-top"><div><div class="pm-task-key">{{ $project->project_number }}</div><h3><a href="{{ route('admin.project-management.projects.show', $project) }}">{{ $project->name }}</a></h3></div><span class="pm-chip {{ $project->overdue_tasks_count ? 'pm-chip--danger' : ($project->status === 'completed' ? 'pm-chip--success' : '') }}">{{ Str::headline($project->status) }}</span></div><div class="pm-project-meta"><span>{{ $project->client_company ?: $project->client_name ?: 'Internal project' }}</span><span>·</span><span>{{ $project->members_count }} members</span><span>·</span><span>{{ $project->tasks_count }} tasks</span></div><div class="pm-progress"><span style="width:{{ $project->progress_percentage }}%"></span></div><div class="pm-project-meta"><strong>{{ $project->progress_percentage }}% complete</strong><span>{{ $project->overdue_tasks_count }} overdue</span><span>Due {{ optional($project->ends_on)->format('M d, Y') ?: 'not set' }}</span></div><div class="pm-actions">@if ($canManageWorkspace)<a class="ghost-button" href="{{ route('admin.project-management.board', $project) }}">Open board</a>@endif<a class="pm-icon-link" href="{{ route('admin.project-management.projects.show', $project) }}">Details →</a></div></article>
        @empty
            <div class="panel pm-empty" style="grid-column:1/-1">No projects match this view.@if ($canCreateProject) <a class="pm-icon-link" href="{{ route('admin.project-management.projects.create') }}">Create the first one →</a>@endif</div>
        @endforelse
    </section>
    <div>{{ $projects->links() }}</div>
    </div>
@endsection
